### ISSUE TITLE
Using ISO 8601 timestamps

### ISSUE THREAD

**Issue by davedittrich** [CyberReboot/packet_cafe#196]
One of the major issues facing analysts is dealing with multiple data sources created in differing local times using timestamps that do not include timezone. Is the time in this timezone, or in UTC? Are timestamps shown This really (really!) reduces efficiency and accuracy.

The industry standard solution to this problem is using ISO 8601 timestamps.

I am converting dates returned from API calls in my own code, but I think this change would be well worth making (and relatively simple) in ``packet-cafe`` itself. You can do this by changing ``datetime.datetime.utcnow()`` calls with ``arrow.utcnow`` in Python code. I can send a PR for that code. I don't know how to best do this within the Javascript code and tests as I don't code in Javascript.

```
$ lim cafe status a42ee6ab-d60b-4d8e-a1df-cb3dc6985c81 deb9facbec7a4ccbb952b957b9ad73ff
+---------------+-------------+----------------------------------+
| Tool          | State       | Timestamp                        |
+---------------+-------------+----------------------------------+
| pcap-stats    | Complete    | 2020-05-08T18:03:01.823649+00:00 |
| pcap-splitter | Complete    | 2020-05-08T18:03:21.538080+00:00 |
| mercury       | Complete    | 2020-05-08T18:03:06.372628+00:00 |
| snort         | Complete    | 2020-05-08T18:03:11.875505+00:00 |
| pcapplot      | In progress | 2020-05-08T18:03:19.514207+00:00 |
| p0f           | In progress | 2020-05-08T18:03:23.474442+00:00 |
| pcap-dot1q    | Complete    | 2020-05-08T18:03:00.643334+00:00 |
| ncapture      | Complete    | 2020-05-08T18:02:56.485207+00:00 |
| networkml     | In progress | 2020-05-08T18:03:20.568981+00:00 |
+---------------+-------------+----------------------------------+
```

**Comment by cglewis** [comment]
@davedittrich thanks for raising this, a PR would be most welcome. I'll look into the javascript side.

**Comment by rashley-iqt** [comment]
I can tackle dealing with the TZ on the javascript side. I already had to kind of kludge aroound it anyway so I know right where that fix needs to be applied.

**Comment by davedittrich** [comment]
Closing issue as PR was accepted.
