### ISSUE TITLE
"delete" route in v1 API

### ISSUE THREAD

**Issue by davedittrich** [CyberReboot/packet_cafe#210]
I know that "stop" is a WIP per the API documentation. Is "delete" also on the list? Could it be added easily?  (I started looking at the code to find how it could be implemented for a PR, but it looks like it may be in the Javascript code?)

In the mean time, it appears that simply deleting files from the Docker shared volume works. I don't see any (ASCII, at least) index files in that directory tree that contain the session or request IDs, though I suspect there may be state *in* the Redis container?

I haven't looked into container logs yet to see if I can narrow down where in the code it might be.

My workaround for development testing now is to bypass the API and manipulate the file system directly:

```
(lim) dittrich at ren in ~/git/packet_cafe on develop
$ lim cafe admin sessions
+--------------------------------------+
| SessionId                            |
+--------------------------------------+
| 30b9ce67-75a4-49e6-b484-c4646b72fbd9 |
| 2d222a53-5b01-4d5e-a659-7da7c21d3cf6 |
| 73d532d7-3b2b-4a93-9a68-ae7091af6a2f |
| 9a949fe6-6520-437f-89ec-e7af6925b1e0 |
| 58a922ac-5483-4502-85b0-84673c473467 |
| 7eedfd93-4f65-4422-8d70-a4edf47d7364 |
| b0cf794e-bd80-4355-bd58-e20ae0473075 |
| a42ee6ab-d60b-4d8e-a1df-cb3dc6985c81 |
+--------------------------------------+
(lim) dittrich at ren in ~/git/packet_cafe on develop
$ for sess_id in $(lim cafe admin sessions -f value | head -n 5)
> do
> rm -rf ~/packet_cafe_data/{files,ids}/$sess_id
> done
(lim) dittrich at ren in ~/git/packet_cafe on develop
$ lim cafe admin sessions
+--------------------------------------+
| SessionId                            |
+--------------------------------------+
| b0cf794e-bd80-4355-bd58-e20ae0473075 |
| a42ee6ab-d60b-4d8e-a1df-cb3dc6985c81 |
| 7eedfd93-4f65-4422-8d70-a4edf47d7364 |
+--------------------------------------+
```

That isn't ideal, I know. Is there any side-effect of doing this?

**Comment by cglewis** [comment]
Hi @davedittrich,

Redis only stores the state of the status of each worker job, so that isn't a concern for what you're doing.  On the Javascript side, it generates the ID and passes it on the API. The only state at that point is the existence of the the directory.

Adding a `/delete/{id}` in the `/admin` API sounds like a good addition, and should just be a matter of deleting the directory of that ID.  Additionally, I could see it being useful to have a "delete all" , which could just be another endpoint implemented in the admin API.

I'm not sure when I'll be able to get around to this, but feel free to open a PR with these proposed enhancements.

**Comment by davedittrich** [comment]
Well, that wasn't as difficult as I anticipated!

> Adding a /delete/{id} in the /admin API sounds like a good addition, and should just be a matter of deleting the directory of that ID.

Thanks for the pointer. That got me where I needed to go. PR coming ASAP...

```
$ lim cafe admin sessions
+--------------------------------------+
| SessionId                            |
+--------------------------------------+
| 1c34e550-2e20-41a5-aaba-4ca83d238bfd |
| 38ad7b06-de83-42c9-aeff-c339dc0a49f9 |
| 94b32839-3406-4c1b-ad88-02dace90c9ec |
+--------------------------------------+
$ lim -q cafe upload test.pcap && lim cafe admin sessions
+--------------------------------------+
| SessionId                            |
+--------------------------------------+
| 1c34e550-2e20-41a5-aaba-4ca83d238bfd |
| eecb8bca-00e8-4d71-9781-16dfa0c00728 |
| 38ad7b06-de83-42c9-aeff-c339dc0a49f9 |
| 94b32839-3406-4c1b-ad88-02dace90c9ec |
+--------------------------------------+
$ lim cafe admin delete && lim cafe admin sessions
[+] implicitly reusing last session id eecb8bca-00e8-4d71-9781-16dfa0c00728
[+] deleted session eecb8bca-00e8-4d71-9781-16dfa0c00728
+--------------------------------------+
| SessionId                            |
+--------------------------------------+
| 1c34e550-2e20-41a5-aaba-4ca83d238bfd |
| 38ad7b06-de83-42c9-aeff-c339dc0a49f9 |
| 94b32839-3406-4c1b-ad88-02dace90c9ec |
+--------------------------------------+
```

> Additionally, I could see it being useful to have a "delete all" , which could just be another endpoint implemented in the admin API.

I'm not sure if adding an additional route to the API just for that is necessary. I already had logic in my CLI for handling multiple session ID arguments (and validating they exist in the current session list), so I just added an ``-all`` option that defaults to the current list of sessions.

```
$ lim cafe admin delete --all && lim cafe admin sessions
[+] deleted session 1c34e550-2e20-41a5-aaba-4ca83d238bfd
[+] deleted session 38ad7b06-de83-42c9-aeff-c339dc0a49f9
[+] deleted session 94b32839-3406-4c1b-ad88-02dace90c9ec

$ tree ~/packet_cafe_data/
/Users/dittrich/packet_cafe_data/
├── definitions
│   └── workers.json
├── files
├── id
└── redis
    └── appendonly.aof

4 directories, 2 files
```

**Comment by cglewis** [comment]
Thanks for implementing this!
